[server]
  port = "8080"
  api_version = "v1"

[logger]
  level = "debug"

[kms]
  regions = [
    "us-east-1",
    "us-east-2",
    "us-west-1"
    ]

  key_ids = {
    us-east-1 = "alias/rkms-us-east-1",
    us-east-2 = "alias/rkms-us-east-2",
    us-west-1 = "alias/rkms-us-west-1" }
  
  data_key_size_in_bytes = 32

[dynamodb]
  region = "us-east-1"
  table_name = "rkms_keys"
  cache_expiration_in_minutes = 5
  cache_cleanup_internal_in_minutes = 10
